apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front-end-virtualservice
spec:
  hosts:
    - front-end-nikhil-sockshop.apps.gvtbmodu.eastus.aroapp.io
  gateways:
    - sockshop-wildcard-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: front-end.nikhil-sockshop.svc.cluster.local
